<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120628094531 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE Organizator (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, event_id INT DEFAULT NULL, INDEX IDX_33D4E3FEA76ED395 (user_id), INDEX IDX_33D4E3FE71F7E88B (event_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE User (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, surname VARCHAR(255) NOT NULL, twitter VARCHAR(255) NOT NULL, twitterid VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_2DA17977166A7BB6 (twitter), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE Attendee (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, event_id INT DEFAULT NULL, INDEX IDX_E826B731A76ED395 (user_id), INDEX IDX_E826B73171F7E88B (event_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE Speaker (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, event_id INT DEFAULT NULL, INDEX IDX_B438E2FDA76ED395 (user_id), INDEX IDX_B438E2FD71F7E88B (event_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE Organizator ADD CONSTRAINT FK_33D4E3FEA76ED395 FOREIGN KEY (user_id) REFERENCES User(id)");
        $this->addSql("ALTER TABLE Organizator ADD CONSTRAINT FK_33D4E3FE71F7E88B FOREIGN KEY (event_id) REFERENCES Event(id)");
        $this->addSql("ALTER TABLE Attendee ADD CONSTRAINT FK_E826B731A76ED395 FOREIGN KEY (user_id) REFERENCES User(id)");
        $this->addSql("ALTER TABLE Attendee ADD CONSTRAINT FK_E826B73171F7E88B FOREIGN KEY (event_id) REFERENCES Event(id)");
        $this->addSql("ALTER TABLE Speaker ADD CONSTRAINT FK_B438E2FDA76ED395 FOREIGN KEY (user_id) REFERENCES User(id)");
        $this->addSql("ALTER TABLE Speaker ADD CONSTRAINT FK_B438E2FD71F7E88B FOREIGN KEY (event_id) REFERENCES Event(id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Organizator DROP FOREIGN KEY FK_33D4E3FEA76ED395");
        $this->addSql("ALTER TABLE Attendee DROP FOREIGN KEY FK_E826B731A76ED395");
        $this->addSql("ALTER TABLE Speaker DROP FOREIGN KEY FK_B438E2FDA76ED395");
        $this->addSql("DROP TABLE Organizator");
        $this->addSql("DROP TABLE User");
        $this->addSql("DROP TABLE Attendee");
        $this->addSql("DROP TABLE Speaker");
    }
}
