<?php

namespace FTF\AttendeeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AttendeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttendeeRepository extends EntityRepository
{
}