<?php

namespace FTF\AttendeeBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * AttendeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttendeeRepository extends EntityRepository
{
    public function clear()
    {
        $query = $this->_em->createQuery('DELETE FTF\AttendeeBundle\Entity\Attendee');
        $query->execute();
    }
    
    public function findAllByTwitteridAndEvent($ids,$event)
    {
        $qb = $this->createQueryBuilder('a')
                ->where("a.event = :eventid")
                ->join('a.user', 'u')
                ->setParameter('eventid', $event->getId());
        if ($ids) {
            $qb->andWhere($qb->expr()->in('u.twitterid', $ids));
        }
        
        return $qb->getQuery()->getResult();
    }
}