<?php

namespace FTF\AttendeeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SpeakerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpeakerRepository extends EntityRepository
{
    public function findAllByTwitteridAndEvent($ids,$event)
    {
        $qb = $this->createQueryBuilder('s')
                ->where("s.event = :eventid")
                ->join('s.user', 'u')
                ->setParameter('eventid', $event->getId());
        if ($ids) {
            $qb->andWhere($qb->expr()->in('u.twitterid', $ids));
        }
        
        return $qb->getQuery()->getResult();
    }
}